

services:
  node:
    build:
      context: .
      ssh:
        - default
      dockerfile: Dockerfile
    container_name: engage-ecommerce-api
    ports:
      - "9000:9000"
    environment:
      STORE_CORS: ${STORE_CORS}
      ADMIN_CORS: ${ADMIN_CORS}
      AUTH_CORS: ${AUTH_CORS}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      REDIS_URL: ${REDIS_URL}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM: ${SENDGRID_FROM}
      SENDGRID_ORDER_PLACED_ID: ${SENDGRID_ORDER_PLACED_ID}
      SENDGRID_CUSTOMER_PASSWORD_RESET_ID: ${SENDGRID_CUSTOMER_PASSWORD_RESET_ID}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      SPACES_URL: ${SPACES_URL}
      SPACES_BUCKET: ${SPACES_BUCKET}
      SPACES_ENDPOINT: ${SPACES_ENDPOINT}
      SPACES_REGION: ${SPACES_REGION}
      SPACES_ACCESS_KEY_ID: ${SPACES_ACCESS_KEY_ID}
      SPACES_SECRET_ACCESS_KEY: ${SPACES_SECRET_ACCESS_KEY}
    depends_on:
      - redis
    restart: always
    networks:
      - engage-network
  
  redis:
    image: redis:7-alpine
    container_name: redis-prod
    restart: always
    networks:
      - engage-network

networks:
  engage-network:
    driver: bridge

